### ISSUE TITLE
Request for ready-to-use dataset and queries

### ISSUE THREAD

**Issue by raywill** [daseECNU/Touchstone#1]
Good job guys!

In order to ease the use of your tool,
can you give several ready to use data-sets (1G/10G/100G/...)
and corresponding queries?

So that we can use other tools to import these data and test queries against the data.

**Comment by LiYuming** [comment]
Hi raywill,

Thank you for your interest.
I may not quite understand what you mean.
Touchstone is a query-aware data generator used to generate test dataset.
The input of Touchstone includes DB schema, data characteristics and workload characteristics.
We give some example inputs for the workload of TPC-H and SSB in order to make it easy to use our tool.
These examples are located in "running examples/input".
You can use these inputs directly to generate test databases and query parameters for the workload of TPC-H and SSB.
Looking forward to your next issue.

LiYuming

**Comment by LiYuming** [comment]
Hi raywill, do you just want some of the datasets we have generated and the corresponding queries?
You can use our generator generates them in your machines, and it is faster than downloading them from the Internet.
